In [9]:
import numpy as np

In [65]:
def to_model(df):
    df = np.array(df)
    tmp = np.power(np.diff(df,axis=0), 2)
    tmp[:,::2] = -tmp[:,::2]
    tmp = np.mean(np.sqrt(np.diff(tmp)[:,::2]), axis=0)
    return (np.concatenate((df.T.reshape((int(df.shape[1] / 2), 10)), np.array([tmp]).T), axis=1)).astype(int)

In [66]:
a

array([[1, 1, 0, 1],
       [2, 2, 0, 2],
       [3, 3, 0, 4],
       [4, 4, 0, 6],
       [5, 5, 0, 7]])

In [67]:
b = to_model(a)

In [68]:
b

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1],
       [0, 0, 0, 0, 0, 1, 2, 4, 6, 7, 1]])

In [63]:
b = b.astype(int)

In [64]:
b

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1],
       [0, 0, 0, 0, 0, 1, 2, 4, 6, 7, 1]])